#!/usr/bin/env node
// Acceptance runner for the native + secrets slice (spec acceptance 1-10). It runs every automated check against the
// installed runtime in an explicit scratch $CUA_HOME, inventories the release gates this machine cannot prove, and
// writes a per-item PASS/FAIL/BLOCKED report. Only a check that ran and passed is PASS; anything skipped, opt-in and
// not requested, or waiting on a human or another environment is BLOCKED with what it needs.
//
//   export CUA_HOME="$(mktemp -d /tmp/cua-accept.XXXXXX)"
//   node bin/cua.mjs install --archive <pinned ChatGPT zip>
//   node scripts/accept-native.mjs [--live-secrets] [--live-textedit] [--archive <zip>] --report "$CUA_HOME/acceptance.json"
//   node scripts/accept-native.mjs --live-secrets --live-textedit --secret-key <KEY> [--secret-home <dir>] --report …
//
// --secret-key types a key the caller stored beforehand (`HOME=<dir> node bin/cua.mjs secrets set <KEY>`) instead of a
// generated one; its store is the one under --secret-home, by default $HOME, which must not be this account's home.
// Pass --secret-home rather than exporting HOME for the whole run: the runner's other native checks (verify.mjs,
// probe-lifecycle) find the computer-use socket under $HOME. The caller's key and home are left in place.
//
// What runs:
//   1  `npm test` in this checkout
//   2  the installed release, its verification, a reinstall that must change nothing (it never downloads: without
//      --archive it passes a path that does not exist, which only a non-verified install would ever read)
//   3  `cua doctor --json` on the installed home and on an empty one
//   4  `node verify.mjs`, plus the native no-account check (the runtime's own CODEX_HOME holds no auth file)
//   5  --live-textedit only: scripts/accept/textedit.mjs (one disposable TextEdit document)
//   6  in a temporary $HOME store only (never ~/.config/claude-secrets): `secrets set` without a terminal, then at a
//      pty (masked, typed twice), `secrets list --json`, `secrets remove`; MCP `secrets_list`; --live-secrets runs
//      scripts/probe-secrets.mjs (generated sentinels in its own temporary $HOME, removed in finally); with both flags
//      the TextEdit fixture also types {{secret:KEY}} into its document and reads it back (target observation): a
//      generated value under a generated key in a temporary $HOME it removes, or the caller's --secret-key
//   7  substitution suites, and the live probe's substitution steps when --live-secrets ran it, with its trusted-root
//      rows: unwritable under the scoped default (a guarantee) and, informational (INFO), what an explicit disabled allows
//   8  lifecycle suites, scripts/probe-lifecycle.mjs (live, read-only), per-connection approvals (--live-textedit)
//   9  release gates: clean machine, cold start, fresh permission onboarding (always BLOCKED here)
//   10 README/plugin/package contents, tracked files, and a clean clone of HEAD running npm test (deleted afterwards)
// The report holds metadata only. Values generated by the live fixtures never leave them; the report is checked for
// them before it is written. Nothing here registers an MCP server or edits ~/.claude. Exit 0 PASS, 1 FAIL, 3 BLOCKED.
import {spawn, execFileSync} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import {existsSync, mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync} from 'node:fs';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseArgs} from 'node:util';
import {loadPins, readInstalledRecord, resolveRuntime, selectPin} from '../src/runtime/manifest.mjs';
import {NATIVE_SOCKET} from '../src/runtime/doctor.mjs';
import {isLabel} from '../src/secrets/label.mjs';
import {fileStore, storeDir} from '../src/secrets/store.mjs';
import {socketHolders} from './probe/lib.mjs';
import {fingerprints, textLeaks} from './probe/leak-scan.mjs';
import {
  approvalObservation, diffSnapshots, doctorHealth, forbiddenPaths, inventoryCheck, missingFromPackage, PROBE_SECRETS_PHASES, probePhasesFor, rollup, scenarioVerdict,
  snapshotTree, suiteVerdict, testReporterEnv, testSummary, tokenLike,
} from './accept/lib.mjs';
import {OWN_STEPS, runTextEdit, SECRET_STEPS} from './accept/textedit.mjs';
import {createStoreHome, generatedKey, isAccountHome, removeStoreHome, seedSecret} from './accept/secret-seed.mjs';

const {values: options} = parseArgs({options: {
  report: {type: 'string'}, 'live-secrets': {type: 'boolean'}, 'live-textedit': {type: 'boolean'}, archive: {type: 'string'},
  'secret-key': {type: 'string'}, 'secret-home': {type: 'string'},
}, strict: true});
const REPO = realpathSync(fileURLToPath(new URL('..', import.meta.url)));
const CLI = join(REPO, 'bin', 'cua.mjs');
// The commit whose evidence (docs/evidence/m2-installer.md) proved download mode; acquisition code unchanged since
// then lets that evidence stand for this run.
const DOWNLOAD_EVIDENCE = {commit: 'bc315bc', doc: 'docs/evidence/m2-installer.md',
  paths: ['src/runtime/install.mjs', 'src/runtime/checks.mjs', 'src/runtime/manifest.mjs', 'src/runtime/layout.mjs', 'runtime/releases']};
const NO_DOWNLOAD_GUARD = '/nonexistent/cua-accept-reinstall-must-not-read-an-archive.zip';

if (!process.env.CUA_HOME) {
  console.error('accept-native: set CUA_HOME to a scratch home with the pinned runtime installed (see the header)');
  process.exit(2);
}
const home = realpathSync(process.env.CUA_HOME);
if ((home + '/').startsWith(REPO + '/')) {
  console.error('accept-native: CUA_HOME must be outside the repository');
  process.exit(2);
}
// The caller's key for the TextEdit secret step, and the store home it lives in.
const callerSecret = options['secret-key'] === undefined ? null : {key: options['secret-key'], home: options['secret-home'] ?? process.env.HOME};
if (options['secret-home'] !== undefined && !callerSecret) {
  console.error('accept-native: --secret-home goes with --secret-key');
  process.exit(2);
}
if (callerSecret && (!options['live-secrets'] || !options['live-textedit'] || !isLabel(callerSecret.key) || isAccountHome(callerSecret.home))) {
  console.error('accept-native: --secret-key <KEY> needs --live-secrets --live-textedit, a key of letters, digits and _, and a store home'
    + ' (--secret-home, else $HOME) that is not this account\'s home');
  process.exit(2);
}

const forbidden = [];   // generated values the report must never contain
const items = [];
const check = (name, status, detail, extra = {}) => ({name, status, detail, ...extra});
const sanitize = text => String(text).split(home).join('$CUA_HOME').split(REPO).join('<repo>').split(homedir()).join('~');
const sh = (command, args, opts = {}) => { try { return execFileSync(command, args, {encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...opts}); } catch (error) { return error.stdout ?? ''; } };

// A child with captured output and a hard time limit. It leads its own process group, so a timeout stops it and what
// it started in that group (npm's test runner, say) and nothing else.
function run(command, args, {cwd = REPO, env = process.env, timeoutMs = 600_000, stdin = 'ignore'} = {}) {
  return new Promise(resolve => {
    const started = Date.now();
    const child = spawn(command, args, {cwd, env, stdio: [stdin, 'pipe', 'pipe'], detached: true});
    let stdout = '', stderr = '';
    child.stdout.on('data', d => { stdout += d; });
    child.stderr.on('data', d => { stderr += d; });
    const timer = setTimeout(() => { try { process.kill(-child.pid, 'SIGKILL'); } catch {} }, timeoutMs);
    child.on('error', error => { clearTimeout(timer); resolve({code: null, error: error.code ?? error.message, stdout, stderr, ms: Date.now() - started}); });
    child.on('exit', (code, signal) => { clearTimeout(timer); resolve({code, signal, timedOut: signal === 'SIGKILL', stdout, stderr, ms: Date.now() - started}); });
  });
}
// Suites run without this run's scratch home or any server setting in their environment.
const suiteEnv = () => Object.fromEntries(Object.entries(process.env).filter(([key]) => key !== 'CUA_HOME' && !key.startsWith('CUA_SHIM_')));
const cuaEnv = extra => ({...process.env, CUA_HOME: home, ...extra});
const parseJson = text => { try { return JSON.parse(text); } catch { return null; } };
const seconds = ms => `${(ms / 1000).toFixed(1)} s`;
const ended = r => r.timedOut ? `timed out after ${seconds(r.ms)}` : `exit ${r.code ?? r.error ?? r.signal}`;
const noisy = text => /\b(ExperimentalWarning|DeprecationWarning|Warning:)/.test(text);

function addItem(id, title, checks, evidence) {
  const item = {id, title, status: rollup(checks.map(c => c.status)), checks};
  if (evidence) item.evidence = evidence;
  items.push(item);
  console.error(`accept-native: ${id}. ${title}: ${item.status}`);
  return item;
}

// --- 1. suites -------------------------------------------------------------------------------------------------
async function suites(cwd, {label}) {
  const out = [];
  const node = await run('npm', ['test'], {cwd, env: testReporterEnv(suiteEnv()), timeoutMs: 300_000});
  const summary = testSummary(node.stdout);
  const {totals} = summary;
  const failed = [...node.stdout.matchAll(/^not ok \d+ - (.*)$/gm)].map(m => m[1]);
  const verdict = suiteVerdict({code: node.code, ...summary});
  out.push(check(`${label}npm test`, verdict.status,
    totals ? `${verdict.reason}; ${totals.fail} failed${failed.length ? ` (${failed.join('; ')})` : ''}, ${totals.skipped} skipped, ${totals.todo} TODO in ${seconds(node.ms)}${noisy(node.stdout + node.stderr) ? '; output has warnings' : ''}` : `${ended(node)}; ${verdict.reason}${failed.length ? ` (failed before that: ${failed.join('; ')})` : ''}`,
    {totals}));
  return out;
}
const state = {};

async function item1() {
  const checks = await suites(REPO, {label: ''});
  state.npmTest = checks[0].status;
  addItem(1, 'npm test', checks);
}

// --- 2. install ----------------------------------------------------------------------------------------------------
// A claim backed by a suite carries that suite's own verdict from item 1: it passes only if the suite executed every
// test and all passed.
const fromSuite = (name, files) => check(name, state.npmTest ?? 'FAIL',
  state.npmTest === 'PASS' ? `covered by npm test (${files.join(', ')}), which executed and passed every test in item 1` : `npm test was ${state.npmTest ?? 'not run'} in item 1; see ${files.join(', ')}`);

async function item2() {
  const checks = [];
  const pin = selectPin(loadPins());
  let runtime;
  try {
    runtime = resolveRuntime({home});
    const record = readInstalledRecord(runtime.root, runtime.manifest);
    checks.push(check('installed release', runtime.release === pin.release ? 'PASS' : 'FAIL',
      `active ${runtime.release} (pin ${pin.release}), installed from ${record.source}, archive sha256 ${record.archive.sha256.slice(0, 12)}…, ${record.archive.length} bytes`));
  } catch (error) {
    checks.push(check('installed release', 'FAIL', `${error.code}: ${sanitize(error.message)}`));
  }
  const doctorChecks = state.doctor?.checks ?? [];
  const verified = ['runtime.files', 'runtime.vendor-manifest', 'runtime.ipc', 'runtime.signatures'].map(name => doctorChecks.find(c => c.name === name));
  checks.push(check('verified private runtime tree', verified.every(c => c?.status === 'pass') ? 'PASS' : 'FAIL',
    verified.map(c => c ? `${c.name} ${c.status}` : 'missing').join('; ') + ` (${sanitize(doctorChecks.find(c => c.name === 'runtime.signatures')?.detail ?? '')})`));
  if (runtime && verified.every(c => c?.status === 'pass')) {
    const before = snapshotTree(runtime.root);
    const reinstall = await run(process.execPath, [CLI, 'install', '--json', '--archive', options.archive ?? NO_DOWNLOAD_GUARD], {env: cuaEnv()});
    const result = parseJson(reinstall.stdout);
    const diff = diffSnapshots(before, snapshotTree(runtime.root));
    checks.push(check('reinstall mutates nothing', reinstall.code === 0 && result?.changed === false && diff.same ? 'PASS' : 'FAIL',
      `install --json → ${result ? `ok ${result.ok}, changed ${result.changed}` : `exit ${reinstall.code}: ${sanitize(reinstall.stderr.trim().split('\n').at(-1) ?? '')}`}; ${before.size} entries compared (type, mode, size, mtime, inode): ${diff.same ? 'identical' : `${diff.added.length} added, ${diff.removed.length} removed, ${diff.changed.length} changed`}`));
  } else checks.push(check('reinstall mutates nothing', 'FAIL', 'not attempted: the installed release does not verify'));
  checks.push(fromSuite('bad hash, length, manifest or signature never activates', ['test/runtime-install.test.mjs', 'test/runtime-manifest.test.mjs', 'test/cli.test.mjs']));
  const changed = sh('git', ['-C', REPO, 'log', '--format=%h', `${DOWNLOAD_EVIDENCE.commit}..HEAD`, '--', ...DOWNLOAD_EVIDENCE.paths]).trim();
  const known = sh('git', ['-C', REPO, 'cat-file', '-t', DOWNLOAD_EVIDENCE.commit]).trim() === 'commit';
  checks.push(check('download mode (official pinned URL)', !known ? 'BLOCKED' : changed ? 'BLOCKED' : 'PASS', !known
    ? 'cannot tell whether the acquisition code changed since the recorded download proof; rerun: CUA_HOME="$(mktemp -d /tmp/cua-download.XXXXXX)" node bin/cua.mjs install'
    : changed ? `acquisition code changed since ${DOWNLOAD_EVIDENCE.commit} (${changed.split('\n').join(', ')}): rerun CUA_HOME="$(mktemp -d /tmp/cua-download.XXXXXX)" node bin/cua.mjs install`
      : `cited, not rerun: ${DOWNLOAD_EVIDENCE.doc} (byte-identical tree from the official URL); acquisition code unchanged since ${DOWNLOAD_EVIDENCE.commit}`,
    {evidence: changed || !known ? 'needs rerun' : 'cited'}));
  addItem(2, 'Pinned install: verified private tree, idempotent reinstall, refusal of bad archives, download mode', checks);
}

// --- 3. doctor -----------------------------------------------------------------------------------------------------
async function item3() {
  const checks = [];
  const r = await run(process.execPath, [CLI, 'doctor', '--json'], {env: cuaEnv()});
  const doctor = parseJson(r.stdout);
  state.doctor = doctor;
  const status = name => doctor?.checks?.find(c => c.name === name)?.status ?? 'missing';
  const required = ['platform', 'runtime.installed', 'runtime.files', 'runtime.vendor-manifest', 'runtime.ipc', 'runtime.signatures'];
  const live = ['helper.live', 'helper.permissions', 'secrets.store'];
  const health = doctorHealth({code: r.code, doctor});
  const healthy = health.healthy && doctor.runtime?.release && required.every(n => status(n) === 'pass');
  checks.push(check('doctor --json on the installed home', healthy && live.every(n => status(n) !== 'missing') ? 'PASS' : 'FAIL',
    `${health.detail}; release ${doctor?.runtime?.release ?? 'none'}; ${[...required, ...live].map(n => `${n} ${status(n)}`).join(', ')}`,
    {checks: doctor?.checks?.map(c => ({name: c.name, status: c.status})) ?? null}));
  checks.push(check('runtime health reported apart from live helper and permission evidence', status('helper.permissions') === 'blocked' && status('helper.live') !== 'missing' ? 'PASS' : 'FAIL',
    `helper.live ${status('helper.live')} and helper.permissions ${status('helper.permissions')} are separate checks; a blocked live check does not fail runtime health`));
  const empty = mkdtempSync('/tmp/cua-accept-empty.');
  try {
    const m = await run(process.execPath, [CLI, 'doctor', '--json'], {env: {...process.env, CUA_HOME: empty}});
    const missing = parseJson(m.stdout);
    const installed = missing?.checks?.find(c => c.name === 'runtime.installed');
    checks.push(check('missing runtime gives install guidance and a nonzero exit', m.code === 1 && installed?.status === 'fail' && /cua install/.test(installed.detail) ? 'PASS' : 'FAIL',
      `exit ${m.code}; runtime.installed ${installed?.status}: ${sanitize(installed?.detail ?? '').replace(empty, '<empty home>')}`));
  } finally { rmSync(empty, {recursive: true, force: true}); }
  checks.push(fromSuite('unsupported platform, incompatible helper, secret store state explicit', ['test/runtime-doctor.test.mjs', 'test/secrets-store.test.mjs']));
  addItem(3, 'doctor --json: release, paths, signatures, compatibility; runtime health apart from live evidence', checks);
}

// --- 4. serve / verify -----------------------------------------------------------------------------------------------
async function item4() {
  const checks = [];
  const r = await run(process.execPath, [join(REPO, 'verify.mjs')], {env: cuaEnv(), timeoutMs: 300_000});
  const report = parseJson(r.stdout.slice(r.stdout.indexOf('{')));
  state.verify = report;
  checks.push(check('node verify.mjs', r.code === 0 && report?.problems?.length === 0 ? 'PASS' : 'FAIL',
    report ? `exit ${r.code}; tools ${report.tools?.join(', ')}; task ${report.task?.sameTaskAcrossCalls ? 'stable across calls' : 'unstable'}, end ${report.task?.end?.status}, repeat ${report.task?.repeatEnd}; problems: ${report.problems.length ? report.problems.map(sanitize).join('; ') : 'none'}` : `exit ${r.code}; no report`));
  const processes = report?.processes;
  checks.push(check('relocated binaries and own configuration; no installed-desktop runtime path', processes?.allExecutablesRelocated && processes.desktopRuntimePaths?.length === 0 ? 'PASS' : 'FAIL',
    processes ? `${processes.ancestry.length} processes (server, anchor, runtime): ${[...new Set(processes.ancestry.map(p => p.executable))].join('; ')}` : 'no process evidence'));
  const codexHome = join(home, 'state', 'codex');
  const authFiles = existsSync(codexHome) ? readdirSync(codexHome, {recursive: true}).map(String).filter(f => /(^|\/)auth[^/]*\.json$/i.test(f)) : [];
  checks.push(check('native without an account (owned empty CODEX_HOME)', authFiles.length === 0 && r.code === 0 ? 'PASS' : 'FAIL',
    authFiles.length ? `auth files present under $CUA_HOME/state/codex: ${authFiles.join(', ')}` : 'the runtime\'s CODEX_HOME ($CUA_HOME/state/codex) holds no auth file and nothing was copied from ~/.codex; the verify run above loaded the vendor API and reached the native helper without any account'));
  addItem(4, 'serve and verify.mjs: four-tool surface on relocated binaries and own configuration', checks,
    report ? {nativeHelper: report.nativeHelper, secretsList: report.secretsList, elicitationsDeclined: report.elicitationsDeclined} : undefined);
}

// --- live scenarios (5, 6, 8) --------------------------------------------------------------------------------------
async function liveSecrets() {
  if (!options['live-secrets']) return null;
  const reportFile = join(home, `probe-secrets-${process.pid}.json`);
  const r = await run(process.execPath, [join(REPO, 'scripts', 'probe-secrets.mjs'), '--report', reportFile], {env: cuaEnv(), timeoutMs: 900_000});
  const probe = existsSync(reportFile) ? parseJson(readFileSync(reportFile, 'utf8')) : null;
  rmSync(reportFile, {force: true});
  if (!probe) return {missing: `scripts/probe-secrets.mjs wrote no report (${ended(r)}): ${sanitize(r.stderr.trim().split('\n').at(-1) ?? '')}`, steps: []};
  return probe;
}

async function liveTextEdit() {
  if (!options['live-textedit']) return null;
  return runTextEdit({home, secret: callerSecret ?? Boolean(options['live-secrets']), forbid: value => forbidden.push(value)});
}

const NOT_REQUESTED = flag => check(`opt-in ${flag}`, 'BLOCKED', `not run: pass ${flag} to run it (never counted as a pass when skipped)`);
const PROBE_STEPS = PROBE_SECRETS_PHASES.flatMap(p => p.steps);
// The live probe's checks: its own complete verdict (a missing report is FAIL), then each expected phase.
function probeChecks(probe, phases) {
  const verdict = probe.missing ? check('live: scripts/probe-secrets.mjs verdict', 'FAIL', probe.missing) : scenarioVerdict('live: scripts/probe-secrets.mjs verdict', probe, PROBE_STEPS);
  return [verdict, ...phases.map(p => inventoryCheck(p.name, probe.steps, p.steps))];
}

async function item5(textedit) {
  if (!textedit) return addItem(5, 'Live native fixture: its own disposable TextEdit document', [NOT_REQUESTED('--live-textedit')]);
  const o = textedit.observations;
  const checks = [
    // Its own steps only (anything else it recorded, an unexpected error say, included); the secret steps are item 6's.
    (own => scenarioVerdict('live TextEdit fixture verdict (own document)', {status: rollup(own.map(x => x.status)), steps: own}, OWN_STEPS))(textedit.steps.filter(x => !SECRET_STEPS.includes(x.name))),
    ...OWN_STEPS.map(step => inventoryCheck(step, textedit.steps, [step])),
  ];
  addItem(5, 'Live native fixture: its own disposable TextEdit document', checks, {
    nativeHelper: o.nativeHelper, textEdit: o.textEdit, screenshot: o.screenshot, elicitations: o.elicitations, connections: o.connections, guiInputStopped: o.guiInputStopped,
    note: 'cold start of the pinned helper is not shown here: see item 9',
  });
}

// Every CLI step runs against a temporary $HOME's store, never the account's ~/.config/claude-secrets.
async function item6(probe, textedit) {
  const checks = [];
  const storeHome = createStoreHome('cua-accept-secrets-');
  const cli = (args, timeoutMs = 30_000) => run(process.execPath, [CLI, 'secrets', ...args], {env: cuaEnv({HOME: storeHome}), timeoutMs});
  const store = fileStore({dir: storeDir({HOME: storeHome})});
  const listed = async () => { try { return await store.list(); } catch { return null; } };
  const key = generatedKey('CUA_ACCEPT_SET');
  const value = `CUASET${randomBytes(12).toString('hex').toUpperCase()}`;
  forbidden.push(value);
  try {
    const noTty = generatedKey('CUA_ACCEPT_NOTTY');
    const set = await cli(['set', noTty]);
    checks.push(check('secrets set requires a terminal', set.code !== 0 && /terminal/i.test(set.stderr) && !(await listed() ?? []).includes(noTty) ? 'PASS' : 'FAIL',
      `without a terminal: exit ${set.code}, "${sanitize(set.stderr.trim().split('\n').at(-1) ?? '')}"; ${(await listed() ?? []).includes(noTty) ? 'a file was created' : 'nothing was stored'}`));

    const seeded = await seedSecret({home: storeHome, key, value});
    let roundTrip = false, modes = '';
    try {
      roundTrip = await store.read(key) === value;
      modes = `directory ${(statSync(store.dir).mode & 0o777).toString(8)}, file ${(statSync(join(store.dir, key)).mode & 0o777).toString(8)}`;
    } catch (error) { modes = `read refused: ${error.code}`; }
    checks.push(check('secrets set at a terminal: masked, typed twice, stored exactly, 0600 in 0700',
      seeded.exit === 0 && seeded.prompts === 2 && !seeded.echoed && roundTrip && modes === 'directory 700, file 600' ? 'PASS' : 'FAIL',
      `on a pty: exit ${seeded.exit ?? seeded.signal}${seeded.timedOut ? ' (timed out)' : ''}, ${seeded.prompts} prompt(s) answered, value ${seeded.echoed ? 'ECHOED' : 'never echoed'}; the file reads back ${roundTrip ? 'exactly the typed value' : 'something else'}; ${modes}`));

    const list = await cli(['list', '--json']);
    const json = parseJson(list.stdout);
    const labelsOnly = list.code === 0 && json && Object.keys(json).sort().join() === 'labels,ok' && json.labels.every(isLabel) && json.labels.includes(key) && !list.stdout.includes(value);
    checks.push(check('secrets list returns keys only', labelsOnly ? 'PASS' : 'FAIL',
      labelsOnly ? `{ok, labels}: the stored key and no value (${json.labels.length} key(s))` : `exit ${list.code}; ${json ? `keys ${Object.keys(json).join(',')}` : 'no JSON'}`));

    const removed = await cli(['remove', key, '--yes']);
    const gone = !(await listed() ?? [key]).includes(key);
    checks.push(check('secrets remove deletes the key\'s file', removed.code === 0 && gone ? 'PASS' : 'FAIL', `exit ${removed.code}; the key is ${gone ? 'gone' : 'still listed'}`));
  } finally {
    const cleaned = await removeStoreHome({home: storeHome, key});
    checks.push(check('the temporary store home is removed', cleaned.keyGone && cleaned.homeGone ? 'PASS' : 'FAIL', cleaned.homeGone ? 'removed' : 'still present'));
  }
  const mcp = state.verify?.secretsList;
  checks.push(check('MCP secrets_list returns keys only', mcp?.status === 'ok' && Number.isInteger(mcp.labelCount) ? 'PASS' : mcp ? 'BLOCKED' : 'FAIL',
    mcp ? `verify.mjs: ${JSON.stringify(mcp)}` : 'verify.mjs produced no secrets_list result'));
  checks.push(fromSuite('masked prompt: no-terminal refusal, nothing echoed, mismatch, empty and cancel store nothing', ['test/secrets-cli.test.mjs']));
  if (!probe) checks.push(NOT_REQUESTED('--live-secrets'));
  else checks.push(...probeChecks(probe, probePhasesFor(6)));
  if (textedit?.scenario === 'live-textedit-with-secret') {
    // The optional UI delivery counts only if it actually happened: each of its steps must have run and passed.
    for (const step of SECRET_STEPS) checks.push(inventoryCheck(`UI delivery (optional, combined): ${step.slice('secret: '.length)}`, textedit.steps, [step]));
  }
  const evidence = {
    ...(probe && !probe.missing ? {liveSecrets: {status: probe.status, key: probe.label, steps: probe.steps, runtimeFiles: probe.runtimeFiles,
      channels: probe.channels?.map(c => ({name: c.name, bytes: c.bytes, containsReference: c.containsReference}))}} : {}),
    ...(textedit?.scenario === 'live-textedit-with-secret' ? {uiDelivery: {key: textedit.observations.secretLabel, callerKey: Boolean(callerSecret)}} : {}),
  };
  addItem(6, 'Secrets: terminal-only masked set, key-only listing, live store roundtrip', checks, Object.keys(evidence).length ? evidence : undefined);
}

async function item7(probe) {
  const checks = [
    fromSuite('exact reference expansion per method, ordinary input, invalid/missing/refused-file rejection before dispatch, value-free errors, unsupported shapes', ['test/services-sky.test.mjs', 'test/secrets-reference.test.mjs', 'test/services-sky-trust.test.mjs']),
    fromSuite('the store reads only a regular, owned, 0600 file without following links; every refusal is classified and value-free', ['test/secrets-store.test.mjs']),
  ];
  if (probe) checks.push(...probeChecks(probe, probePhasesFor(7)));
  addItem(7, 'Native input substitution: methods, rejection before dispatch, store refusals', checks);
}

async function item8(textedit) {
  const checks = [fromSuite('lifecycle state machine, races, deadlines, EOF, elicitation routing, bounded teardown', ['test/mcp-lifecycle.test.mjs', 'test/mcp-server.test.mjs', 'test/mcp-upstream.test.mjs', 'test/serve-cli.test.mjs'])];
  const r = await run(process.execPath, [join(REPO, 'scripts', 'probe-lifecycle.mjs')], {env: cuaEnv(), timeoutMs: 300_000});
  const p = parseJson(r.stdout.slice(r.stdout.indexOf('{')));
  if (!p) checks.push(check('native cancel/end_task behaviour observed (probe-lifecycle)', 'FAIL', `exit ${r.code}; no report: ${sanitize(r.stderr.trim().split('\n').at(-1) ?? '')}`));
  else {
    const expectations = [
      ['cancel does not stop a running cell (it replies normally)', p.cancelDuringJs?.reply && !p.cancelDuringJs.reply.isError],
      ['end_task after a cancelled cell ends', p.cancelDuringJs?.endTask?.status === 'ended'],
      ['end_task with work in flight rejects new work as task_ending and ends after it', !p.endTaskWithWorkInFlight?.work?.isError && p.endTaskWithWorkInFlight?.lateWork?.structured?.code === 'task_ending' && p.endTaskWithWorkInFlight?.endTask?.structured?.status === 'ended'],
      ['uncertain completion fails closed (completion_timeout, native cleanup unconfirmed, exit 1, no runtime left)', p.uncertainCompletion?.endTask?.structured?.code === 'completion_timeout' && p.uncertainCompletion.endTask.structured.nativeCleanup === 'unconfirmed' && p.uncertainCompletion.exit?.code === 1 && p.uncertainCompletion.runtimeProcessesAfterExit === 0],
      ['idle EOF closes cleanly with no runtime left', p.idleClose?.code === 0 && p.idleClose.runtimeProcessesAfterExit === 0],
    ];
    for (const [name, ok] of expectations) checks.push(check(`observed: ${name}`, ok ? 'PASS' : 'FAIL', ok ? 'as documented in docs/evidence/m3-mcp-lifecycle.md' : 'differs from the documented behaviour'));
    state.lifecycle = {cancelReplyMs: p.cancelDuringJs?.reply ? p.cancelDuringJs.reply.atMs - p.cancelDuringJs.cancelAtMs : null,
      uncertainExitCode: p.uncertainCompletion?.exit?.code, idleCloseMs: p.idleClose?.closeMs};
  }
  if (!textedit) checks.push(check('per-connection app approvals observed', 'BLOCKED', 'observed only by the live TextEdit fixture: pass --live-textedit'));
  else {
    const observed = approvalObservation(textedit.observations.connections);
    const files = textedit.observations.sessionFiles;
    checks.push(check('per-connection app approvals observed', observed.status, `${observed.detail}; session files under $CUA_HOME/state/codex/computer-use/sessions: ${files.before} before, ${files.after} after`));
  }
  addItem(8, 'Task lifecycle: IDs, end_task outcomes, fail-closed completion; native cancel/approval behaviour observed', checks, state.lifecycle);
}

// --- 9. release gates ------------------------------------------------------------------------------------------------
function item9() {
  const desktop = existsSync('/Applications/ChatGPT.app');
  const desktopRunning = sh('/usr/bin/pgrep', ['-x', 'ChatGPT']).trim().length > 0;
  const holders = existsSync(NATIVE_SOCKET) ? socketHolders(sh('/usr/sbin/lsof', ['-F', 'pc', NATIVE_SOCKET])) : [];
  const holder = holders.map(h => sh('/bin/ps', ['-o', 'comm=', '-p', String(h.pid)]).trim().replace(homedir(), '~')).join(', ');
  addItem(9, 'Release gates this host cannot prove (each blocked individually)', [
    check('clean macOS machine/VM without the desktop app: install, permissions, native fixture, real secret substitution', 'BLOCKED',
      `this host has ChatGPT.app ${desktop ? 'installed' : 'absent'}${desktopRunning ? ' and running' : ''}. Needs: a clean macOS arm64 VM or machine with no ChatGPT/Codex installed, where a human runs install, grants Accessibility and Screen Recording when macOS asks, then accept-native --live-textedit --live-secrets`),
    check('cold start of the pinned native helper', 'BLOCKED',
      `the native socket is held by ${holder || 'nothing right now'}; this run reused whatever helper served and never stops one. Needs: an environment where no other installation's helper runs (the clean VM above), so the pinned helper's LaunchServices start is what serves`),
    check('fresh permission (TCC) onboarding', 'BLOCKED',
      'this account already granted the helper bundle id; existing grants are not evidence of the first-run flow. Needs: a fresh macOS user account or VM where a human answers the Accessibility and Screen Recording prompts'),
  ]);
}

// --- 10. packaging ---------------------------------------------------------------------------------------------------
async function item10() {
  const checks = [];
  const readme = readFileSync(join(REPO, 'README.md'), 'utf8');
  const needed = ['npm test', 'cua.mjs install', 'doctor', 'secrets set', 'claude-secrets', 'serve', 'claude mcp add', 'accept-native.mjs', 'Chrome'];
  const absent = needed.filter(text => !readme.includes(text));
  checks.push(check('README: standalone requirements, limitations and exact commands', absent.length ? 'FAIL' : 'PASS', absent.length ? `missing: ${absent.join(', ')}` : `mentions ${needed.join(', ')}`));
  const plugin = parseJson(readFileSync(join(REPO, '.claude-plugin', 'plugin.json'), 'utf8'));
  const server = plugin?.mcpServers?.cua_repl;
  const pluginOk = server?.command === 'node' && server.args?.some(a => a.endsWith('/cua-shim.mjs')) && !plugin.hooks && !existsSync(join(REPO, 'hooks'));
  checks.push(check('plugin launches the standalone server; no Stop/SubagentStop hooks', pluginOk ? 'PASS' : 'FAIL', `cua_repl: ${server ? `${server.command} ${server.args.join(' ')}` : 'missing'}; hooks ${plugin?.hooks || existsSync(join(REPO, 'hooks')) ? 'present' : 'none'}`));

  const tracked = sh('git', ['-C', REPO, 'ls-files']).split('\n').filter(Boolean);
  const badTracked = forbiddenPaths(tracked);
  const userHome = homedir();
  const code = tracked.filter(p => !p.startsWith('docs/') && !/\.md$/.test(p) && existsSync(join(REPO, p)));
  const personal = code.filter(p => { const text = readFileSync(join(REPO, p), 'latin1'); return text.includes(userHome + '/') || tokenLike(text); });
  checks.push(check('nothing tracked is an archive, runtime, credential, log or machine-specific token', tracked.length && !badTracked.length && !personal.length ? 'PASS' : 'FAIL',
    `${tracked.length} tracked files; forbidden: ${badTracked.join(', ') || 'none'}; code/config naming this user's home or holding token-like strings: ${personal.join(', ') || 'none'}`));

  const pack = await run('npm', ['pack', '--dry-run', '--json'], {env: suiteEnv()});
  const packed = parseJson(pack.stdout);
  const entry = Array.isArray(packed) ? packed[0] : packed && Object.values(packed)[0];
  const files = entry?.files?.map(f => f.path) ?? [];
  const missing = missingFromPackage(files);
  const badPacked = forbiddenPaths(files);
  const untracked = files.filter(f => !tracked.includes(f));
  checks.push(check('package files: what runs and diagnoses; nothing else', files.length && !missing.length && !badPacked.length && !untracked.length ? 'PASS' : 'FAIL',
    `${files.length} files${missing.length ? `; missing ${missing.join(', ')}` : ''}${badPacked.length ? `; forbidden ${badPacked.join(', ')}` : ''}${untracked.length ? `; untracked ${untracked.join(', ')}` : ''}`));

  const spawnsClaude = code.filter(p => /\.(mjs|js|json|sh)$/.test(p)).filter(p => /spawn\w*\(\s*['"]claude['"]|exec\w*\(\s*['"]claude['"]|['"]claude['"],\s*\[['"]mcp['"]/.test(readFileSync(join(REPO, p), 'utf8')));
  checks.push(check('existing MCP registration untouched', spawnsClaude.length ? 'FAIL' : 'PASS',
    spawnsClaude.length ? `code that runs claude: ${spawnsClaude.join(', ')}` : 'no tracked code runs `claude` or edits ~/.claude; registration is documented (README) and never executed by acceptance'));

  const head = sh('git', ['-C', REPO, 'rev-parse', '--short', 'HEAD']).trim();
  const branch = sh('git', ['-C', REPO, 'rev-parse', '--abbrev-ref', 'HEAD']).trim();
  const dirty = sh('git', ['-C', REPO, 'status', '--porcelain']).trim().length > 0;
  const clone = mkdtempSync('/tmp/cua-clean.');
  try {
    const cloned = await run('git', ['clone', '--quiet', '--branch', branch, REPO, join(clone, 'cua')], {cwd: clone, timeoutMs: 120_000});
    if (cloned.code !== 0) checks.push(check('clean clone tests', 'FAIL', `git clone failed: ${cloned.stderr.trim()}`));
    else {
      const dir = join(clone, 'cua');
      checks.push(...await suites(dir, {label: 'clean clone: '}));
      // This runner holds the pattern itself, so it is not searched.
      const researchRefs = sh('git', ['-C', dir, 'grep', '-l', '-e', 'codex-app-src', '--', ':!docs', ':!*.md', ':!scripts/accept-native.mjs']).trim();
      checks.push(check('clean clone needs no research trees', researchRefs ? 'FAIL' : 'PASS', researchRefs ? `code referring to research trees: ${researchRefs}` : 'no code or config outside docs refers to the local research trees'));
    }
  } finally { rmSync(clone, {recursive: true, force: true}); }
  addItem(10, 'Packaging, plugin README, tracked files, clean checkout', checks, {head, branch, workingTreeDirty: dirty, cloneRemoved: !existsSync(clone)});
}

// --- run -------------------------------------------------------------------------------------------------------------
const started = new Date();
const runDirBefore = existsSync(join(home, 'run')) ? readdirSync(join(home, 'run')) : [];
await item1();
await item3();          // doctor first: item 2 reads its verification result
await item2();
await item4();
const probe = await liveSecrets();
const textedit = await liveTextEdit();
await item5(textedit);
await item6(probe, textedit);
await item7(probe);
await item8(textedit);
item9();
await item10();
items.sort((a, b) => a.id - b.id);

const runLeftovers = (existsSync(join(home, 'run')) ? readdirSync(join(home, 'run')) : []).filter(name => !runDirBefore.includes(name));
const report = {
  scenario: 'accept-native', status: rollup(items.map(i => i.status)),
  options: {liveSecrets: Boolean(options['live-secrets']), liveTextedit: Boolean(options['live-textedit']), callerSecretKey: Boolean(callerSecret)},
  release: state.doctor?.runtime?.release ?? null, home: '$CUA_HOME', host: `${process.platform}-${process.arch}`, node: process.version,
  startedAt: started.toISOString(), finishedAt: new Date().toISOString(),
  summary: Object.fromEntries(items.map(i => [i.id, i.status])),
  connectionDirectoriesLeft: runLeftovers.length,
  items,
};
const text = JSON.stringify(report, (key, value) => typeof value === 'string' ? sanitize(value) : value, 2);
if (textLeaks(text, forbidden.flatMap(fingerprints))) {
  console.error('accept-native: refusing to write a report containing a generated value');
  process.exit(1);
}
if (options.report) writeFileSync(options.report, text + '\n', {mode: 0o600});
console.log(text);
process.exit(report.status === 'PASS' ? 0 : report.status === 'FAIL' ? 1 : 3);
